# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f1614197e202f4a0dbfba4b9d318f6f6451bb8ae3fa1b72fbba31c7668a9735382579bc31e464c373d554ff40891798cc261adbafded467c56465b3f6c14479

test:
  secret_key_base: 57f8091e9cd4fc8e78b0456b30c295ae26403e67e73457f79bf86c2abde8dfd23da7ce5a0c74d5585492adaeecd3b6c882203c48a36230ced6a3e32aec053dd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
